const { VITE_THEME_SECONDARY_BLUE, VITE_THEME_SECONDARY_PURPLE, VITE_THEME_SECONDARY_YELLOW,
    VITE_THEME_SECONDARY_ORANGE, VITE_THEME_SECONDARY_TEAL, VITE_THEME_SECONDARY_LIGHT_GREEN,
    VITE_THEME_PRIMARY_GREY_400 } = import.meta.env;

export const FIELD_TYPE_COLOURS: { [key: string]: string } = {
  string: VITE_THEME_SECONDARY_BLUE,
  categorical: VITE_THEME_SECONDARY_PURPLE,
  number: VITE_THEME_SECONDARY_YELLOW,
  double: VITE_THEME_SECONDARY_ORANGE,
  boolean: VITE_THEME_SECONDARY_TEAL,
  date: VITE_THEME_SECONDARY_LIGHT_GREEN,
  default: VITE_THEME_PRIMARY_GREY_400,
} as const;

export type FieldType = keyof typeof FIELD_TYPE_COLOURS;
